# Change baseurl before deploy
baseurl = "https://blog.liaoke.xyz"
title = "LiaoKE"
buildFuture = true
enableGitInfo = true
math = true

# Theme i18n support
# See all available values at https://github.com/CaiJimmy/hugo-theme-stack/tree/master/i18n
defaultContentLanguage = "zh"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
hasCJKLanguage = true

# Change it to your Disqus shortname before using
disqusShortname = "hugo-theme-stack"

[pagination]
pagerSize = 10

[frontmatter]
  lastmod = [':fileModTime']
  date = [':filename',':default']
  publishDate = [':filename',':default']

[params]
  timeZone = "Asia/Shanghai"

[sitemap]
  changeFreq = "always"
  filename   = "sitemap.xml"
  priority   = -1
