# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "qq"
weight = 8
name = "QQ"
url = "https://qm.qq.com/q/cIB4E2ldFC"

[social.params]
icon = "qq"

[[social]]
identifier = "github"
weight = 9
name = "GitHub"
url = "https://github.com/iliaoke"

[social.params]
icon = "brand-github"


[[social]]
identifier = "email"
weight = 99
name = "Email"
url = "mailto:liaoke2007@gmail.com"

[social.params]
icon = "mail"

#[[social]]
#identifier = "twitter"
#weight = 9999
#name = "Twitter"
#url = "https://x.com/liaoke321"

#[social.params]
#icon = "brand-twitter"

[[social]]
identifier = "rss"
weight = 999999
name = "Rss"
url = "https://blog.liaoke.xyz/index.xml"

[social.params]
icon = "rss"



