# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon        = "img/favicon.png"

# Accepted values: "default", "lastmod"
# default = see https://gohugo.io/quick-reference/glossary/#default-sort-order
# lastmod = sort by last modified date, in descending order
SortBy              = "default"

[footer]
since = 2025
customText = ""

[dateFormat]
published = ""
lastUpdated = ""

[sidebar]
emoji = "üç•"
subtitle = "ÂñúÊ¨¢Êé¢Á¥¢Êú™Áü•ÁöÑÈ¢ÜÂüü"
avatar   = "img/avatar.png"

[article]
    headingAnchor = false
    math          = false
    readingTime   = true

    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[opengraph.twitter]
    site = ""
    card = "summary_large_image"

[colorScheme]
    toggle  = true
    default = "auto"

## Comments
[comments]
enabled = true
provider = "waline"

    # See all the available configurations at https://github.com/CaiJimmy/hugo-theme-stack/blob/master/config/_default/params.toml
    # Copy the configurations you need from there and paste it here.

[comments.waline]
        serverURL = "https://comment.liaoke.xyz"
        lang = "zh-CN"
        pageview = true
        emoji = [
            "https://unpkg.com/@waline/emojis@1.4.0/weibo"
        ]
        requiredMeta = [
            "name",
            "email",
            "url"
        ]
[comments.waline.locale]
            admin = "Admin"
            placeholder = ""
